var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1b2fbc81._.js")
R.c("server/chunks/ssr/_d25179f9._.js")
R.c("server/chunks/ssr/_27f38564._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d65d3be1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_241c23c8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4a0abb1d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__472a4e77._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_bc6b8ddf._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__f0320c61._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_8949c683._.js")
R.m(43660)
module.exports=R.m(43660).exports
